---
name: CI

on:
  push:

jobs:
  Continuous-Integration:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Use Node.js 16.16.0
      uses: actions/setup-node@v1
      with:
        node-version: '16.16.0'
    - name: Install Modules ('npm install')
      run: npm install
    - name: Run linter (ts-standard)
      run: npx ts-standard
    - name: Execute Tests and Coverage ('npm run coverage')
      run: npm test
    - name: Transpile Typescript (tsc)
      run: tsc --build --verbose
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    - name: Clean up dist folder (?) 
      run: ls ./dist
    - name: Deploy dist to server(s) (?) 
      run: ls ./dist/src
