---
name: CI

on:
  push:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js 16.x
      uses: actions/setup-node@v1
      with:
        node-version: '16.x'
        
    - name: Install, Lint, Test, and Build
      run: |
        npm install
        npx ts-standard
        npm run build --if-present
        npm run test --if-present

    - name: Sonar Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    - name: Sonar Build Breaker
      uses: jkumar19/sonar-build-breaker@v1.0.0
      with:
        sonar_url: "https://sonarcloud.io"
        sonar_branch: "dev"
        sonar_token: ${{ secrets.SONAR_TOKEN }}
        project_key: "Eyesore-Gaming_junkbot-game-server"

    - name: Clean up dist folder (?) 
      run: ls ./dist

    - name: Deploy dist to server(s) (?) 
      run: ls ./dist/src

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v2
      with:
        name: node-app
        path: .

  deploy:
    runs-on: ubuntu-latest
    needs: validate
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifacts from 'validate' job
        uses: actions/download-artifact@v2
        with:
          name: node-app

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'junkbot-game-server'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_D058253CA8D54654BE629225DB1CB6B6 }}
          package: .
